Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
[Train epoch] 1:   0%|          | 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 174, in <module>
    trainer.train(train_loader, val_loader)
  File "main.py", line 139, in train
    avg_loss = self.train_one_epoch(epoch+1, train_loader)
  File "main.py", line 45, in train_one_epoch
    out = self.clf_head(self.encoder(img))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nishant/Desktop/Desktop/Papers2code/Implementations/RotNet-PyTorch/code/models.py", line 50, in forward
    out = self.backbone(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 5-dimensional input of size [128, 4, 3, 32, 32] instead
