2020-12-15 21:39:44,496 INFO    MainThread:518349 [internal.py:wandb_internal():62] W&B internal server running at pid: 518349
2020-12-15 21:39:44,498 DEBUG   HandlerThread:518349 [handler.py:handle_request():54] handle_request: check_version
2020-12-15 21:39:44,498 INFO    WriterThread:518349 [datastore.py:open_for_write():76] open: wandb/run-20201215_213944-236ahogc/run-236ahogc.wandb
2020-12-15 21:39:44,498 DEBUG   SenderThread:518349 [sender.py:send():88] send: header
2020-12-15 21:39:44,498 DEBUG   SenderThread:518349 [sender.py:send():88] send: request
2020-12-15 21:39:44,498 DEBUG   SenderThread:518349 [sender.py:send_request():97] send_request: check_version
2020-12-15 21:39:44,499 DEBUG   Thread-4  :518349 [connectionpool.py:_new_conn():957] Starting new HTTPS connection (1): pypi.org:443
2020-12-15 21:39:44,994 WARNING MainThread:518349 [internal.py:wandb_internal():116] Internal process interrupt: 1
2020-12-15 21:39:45,178 WARNING MainThread:518349 [internal.py:wandb_internal():116] Internal process interrupt: 2
2020-12-15 21:39:45,178 ERROR   MainThread:518349 [internal.py:wandb_internal():119] Internal process interrupted.
2020-12-15 21:39:45,498 INFO    WriterThread:518349 [datastore.py:close():257] close: wandb/run-20201215_213944-236ahogc/run-236ahogc.wandb
2020-12-15 21:39:45,499 INFO    HandlerThread:518349 [handler.py:finish():267] shutting down handler
2020-12-15 21:39:47,101 DEBUG   Thread-4  :518349 [connectionpool.py:_make_request():428] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 52216
2020-12-15 21:39:48,709 INFO    SenderThread:518349 [sender.py:finish():583] shutting down sender
2020-12-15 21:39:48,710 INFO    MainThread:518349 [internal.py:handle_exit():137] Internal process exited
