2020-12-15 21:39:44,044 INFO    MainThread:518267 [wandb_init.py:_log_setup():292] Logging user logs to wandb/run-20201215_213944-236ahogc/logs/debug.log
2020-12-15 21:39:44,044 INFO    MainThread:518267 [wandb_init.py:_log_setup():293] Logging internal logs to wandb/run-20201215_213944-236ahogc/logs/debug-internal.log
2020-12-15 21:39:44,044 INFO    MainThread:518267 [wandb_setup.py:_flush():68] setting env: {}
2020-12-15 21:39:44,044 INFO    MainThread:518267 [wandb_setup.py:_flush():68] setting user settings: {}
2020-12-15 21:39:44,044 INFO    MainThread:518267 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-12-15 21:39:44,994 WARNING MainThread:518267 [wandb_init.py:init():483] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 463, in init
    run = wi.init()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 366, in init
    ret = backend.interface.communicate_check_version()
  File "/usr/local/lib/python3.8/dist-packages/wandb/interface/interface.py", line 595, in communicate_check_version
    result = self._communicate(rec)
  File "/usr/local/lib/python3.8/dist-packages/wandb/interface/interface.py", line 437, in _communicate
    return future.get(timeout)
  File "/usr/local/lib/python3.8/dist-packages/wandb/interface/interface.py", line 58, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2020-12-15 21:39:44,996 INFO    MainThread:518267 [internal.py:handle_exit():137] Internal process exited
